// src/lib/components/charts/DynamicExpenseChart.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import ExpenseChart from './ExpenseChart.svelte';
  import Card from '$lib/components/ui/Card.svelte';

  export let expenseData: Record<string, number>;
  export let isLoading: boolean;

  let mounted = false;

  onMount(() => {
    mounted = true;
  });
</script>

{#if mounted}
  <ExpenseChart expenses={Object.entries(expenseData).map(([id, amount]) => ({
    id,
    amount,
    category: id,
    date: new Date().toISOString()
  }))} {isLoading} />
{:else}
  <Card>
    <header class="px-6 py-4 border-b border-border">
      <h3 class="text-lg font-semibold">Expense Breakdown</h3>
    </header>
    <div class="p-6">
      <div class="h-64 flex items-center justify-center">
        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary" />
      </div>
    </div>
  </Card>
{/if}

// client/src/components/charts/dynamic-expense-chart.tsx
import { lazy, Suspense } from 'react';
import { Loader2 } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

// Dynamically import the ExpenseChart component
const ExpenseChart = lazy(() => import('./expense-chart'));

// Define the props interface
interface ExpenseChartProps {
  expenseData: Record<string, number>;
  isLoading: boolean;
}

// Loading fallback component
const ChartLoadingFallback = () => (
  <Card className="h-full">
    <CardHeader className="pb-2">
      <CardTitle className="text-lg">Expense Breakdown</CardTitle>
    </CardHeader>
    <CardContent className="p-4">
      <div className="h-64 flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    </CardContent>
  </Card>
);

// Wrapper component that uses Suspense
export default function DynamicExpenseChart(props: ExpenseChartProps) {
  return (
    <Suspense fallback={<ChartLoadingFallback />}>
      <ExpenseChart {...props} />
    </Suspense>
  );
}
