// src/lib/components/charts/ExpenseTrendChart.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import Chart from 'chart.js/auto';
  import 'chartjs-adapter-date-fns'; // Import date adapter
  import { Card, CardContent, CardHeader, CardTitle } from '$lib/components/ui/card'; // Assuming shadcn-svelte
  import { Tabs, TabsContent, TabsList, TabsTrigger } from '$lib/components/ui/tabs'; // Assuming shadcn-svelte
  import { format, subDays, eachDayOfInterval, parseISO, startOfDay } from 'date-fns';
  import type { Expense } from '../../../shared/schema'; // Use shared schema type

  export let expenses: Expense[] = [];
  export let isLoading: boolean = false;

  type TimeFrame = '7d' | '30d' | '90d';

  let canvasElement: HTMLCanvasElement;
  let chartInstance: Chart | null = null;
  let activeTimeFrame: TimeFrame = '30d'; // Default timeframe

  // --- Reactive Data Processing ---
  $: chartDataProcessed = processChartData(expenses);

  function processChartData(expenseData: Expense[]) {
    if (!expenseData || !expenseData.length) return null;

    const calculateMovingAverage = (data: { date: string; amount: number }[], days: number) => {
      return data.map((entry, index, arr) => {
        const start = Math.max(0, index - days + 1);
        const subset = arr.slice(start, index + 1);
        const sum = subset.reduce((acc, curr) => acc + curr.amount, 0);
        return sum / subset.length; // Return only the average value
      });
    };

    const generateTimeFrameData = (days: number) => {
      const endDate = startOfDay(new Date()); // Use start of today for consistency
      const startDate = startOfDay(subDays(endDate, days - 1));

      const dateRange = eachDayOfInterval({ start: startDate, end: endDate });

      const dailyTotalsMap = new Map<string, number>();
      dateRange.forEach(date => {
        dailyTotalsMap.set(format(date, 'yyyy-MM-dd'), 0);
      });

      expenseData.forEach(expense => {
        try {
          const expenseDate = startOfDay(parseISO(expense.date));
          const dateString = format(expenseDate, 'yyyy-MM-dd');
          const cost = parseFloat(expense.cost);

          if (dailyTotalsMap.has(dateString) && !isNaN(cost)) {
             dailyTotalsMap.set(dateString, (dailyTotalsMap.get(dateString) || 0) + cost);
          }
        } catch (e) {
            console.error(`Invalid date format for expense ${expense.id}: ${expense.date}`);
        }
      });

      // Convert map back to array sorted by date for chart.js and moving average calculation
      const dailyData = Array.from(dailyTotalsMap.entries())
                           .map(([date, amount]) => ({ date, amount }))
                           .sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());


      const movingAverages = calculateMovingAverage(dailyData, 7);

      return {
        labels: dailyData.map(d => d.date), // Use date strings as labels
        dailyAmounts: dailyData.map(d => d.amount),
        movingAverages: movingAverages
      };
    };

    return {
      '7d': generateTimeFrameData(7),
      '30d': generateTimeFrameData(30),
      '90d': generateTimeFrameData(90)
    };
  }

  // --- Chart Rendering ---
  function renderChart() {
    if (!canvasElement || !chartDataProcessed) return;

    const dataForTimeframe = chartDataProcessed[activeTimeFrame];
    if (!dataForTimeframe) return;

    const ctx = canvasElement.getContext('2d');
    if (!ctx) return;

    // Destroy previous instance if exists
    chartInstance?.destroy();

    chartInstance = new Chart(ctx, {
      type: 'line',
      data: {
        labels: dataForTimeframe.labels,
        datasets: [
          {
            label: 'Daily Total',
            data: dataForTimeframe.dailyAmounts,
            borderColor: '#2563eb', // Blue
            backgroundColor: 'rgba(37, 99, 235, 0.1)',
            tension: 0.1,
            fill: true,
          },
          {
            label: '7-Day Average',
            data: dataForTimeframe.movingAverages,
            borderColor: '#16a34a', // Green
            borderDash: [5, 5],
            tension: 0.1,
            fill: false,
          }
        ]
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        scales: {
          x: {
            type: 'time',
            time: {
              unit: activeTimeFrame === '7d' ? 'day' : 'week', // Adjust unit based on timeframe
              tooltipFormat: 'MMM d, yyyy',
              displayFormats: {
                 day: 'MMM d',
                 week: 'MMM d'
              }
            },
            title: {
              display: true,
              text: 'Date'
            }
          },
          y: {
            beginAtZero: true,
            title: {
              display: true,
              text: 'Amount (USD)' // TODO: Make currency dynamic
            },
            ticks: {
               callback: function(value) {
                 // Format as currency
                 return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', notation: 'compact' }).format(Number(value));
               }
            }
          }
        },
        plugins: {
          legend: {
            position: 'top',
          },
          tooltip: {
            mode: 'index',
            intersect: false,
            callbacks: {
              label: function(context) {
                let label = context.dataset.label || '';
                if (label) {
                  label += ': ';
                }
                if (context.parsed.y !== null) {
                  label += new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(context.parsed.y);
                }
                return label;
              }
            }
          }
        },
        interaction: {
          mode: 'index',
          intersect: false,
        },
      }
    });
  }

  // Update chart when timeframe or data changes
  $: if (canvasElement && chartDataProcessed) {
      renderChart();
  }

  onMount(() => {
    renderChart(); // Initial render
  });

  onDestroy(() => {
    chartInstance?.destroy();
  });

</script>

<Card>
  <CardHeader>
    <CardTitle>Expense Trends</CardTitle>
  </CardHeader>
  <CardContent>
    {#if isLoading}
      <div class="h-[400px] flex items-center justify-center">
        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
      </div>
    {:else if !chartDataProcessed}
      <div class="h-[400px] flex items-center justify-center text-muted-foreground">
        No expense data available for trend analysis.
      </div>
    {:else}
      <Tabs bind:value={activeTimeFrame} class="space-y-4">
        <TabsList>
          <TabsTrigger value="7d">7 Days</TabsTrigger>
          <TabsTrigger value="30d">30 Days</TabsTrigger>
          <TabsTrigger value="90d">90 Days</TabsTrigger>
        </TabsList>

        <!-- Chart Canvas (only one needed, data updates reactively) -->
        <div class="h-[400px] relative">
           <canvas bind:this={canvasElement}></canvas>
        </div>
      </Tabs>
    {/if}
  </CardContent>
</Card>

// client/src/components/charts/expense-trend-chart.tsx
import React, { useMemo } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "../ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "../ui/tabs";
import {
  Line,
  LineChart,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer
} from 'recharts';
import { format, subDays, eachDayOfInterval } from 'date-fns';

interface Expense {
  id: string;
  amount: number;
  category: string;
  date: string;
}

interface ExpenseTrendChartProps {
  expenses: Expense[];
  isLoading: boolean;
}

type TimeFrame = '7d' | '30d' | '90d';

export default function ExpenseTrendChart({ expenses, isLoading }: ExpenseTrendChartProps) {
  const chartData = useMemo(() => {
    if (!expenses.length) return null;

    const calculateMovingAverage = (data: { date: string; amount: number }[], days: number) => {
      return data.map((entry, index) => {
        const start = Math.max(0, index - days + 1);
        const subset = data.slice(start, index + 1);
        const sum = subset.reduce((acc, curr) => acc + curr.amount, 0);
        return {
          ...entry,
          movingAverage: sum / subset.length
        };
      });
    };

    const generateTimeFrameData = (days: number) => {
      const endDate = new Date();
      const startDate = subDays(endDate, days - 1);

      // Create array of all dates in range
      const dateRange = eachDayOfInterval({ start: startDate, end: endDate });
      
      // Initialize daily totals
      const dailyData = dateRange.map(date => ({
        date: format(date, 'yyyy-MM-dd'),
        amount: 0,
        count: 0
      }));

      // Aggregate expenses by date
      expenses.forEach(expense => {
        const expenseDate = expense.date.split('T')[0];
        const dayData = dailyData.find(d => d.date === expenseDate);
        if (dayData) {
          dayData.amount += expense.amount;
          dayData.count += 1;
        }
      });

      // Calculate moving averages
      return calculateMovingAverage(dailyData, 7);
    };

    return {
      '7d': generateTimeFrameData(7),
      '30d': generateTimeFrameData(30),
      '90d': generateTimeFrameData(90)
    };
  }, [expenses]);

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(amount);
  };

  const formatDate = (dateStr: string) => {
    return format(new Date(dateStr), 'MMM d');
  };

  if (isLoading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Expense Trends</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="h-[400px] flex items-center justify-center">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
          </div>
        </CardContent>
      </Card>
    );
  }

  if (!chartData) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Expense Trends</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="h-[400px] flex items-center justify-center text-muted-foreground">
            No expense data available
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Expense Trends</CardTitle>
      </CardHeader>
      <CardContent>
        <Tabs defaultValue="30d" className="space-y-4">
          <TabsList>
            <TabsTrigger value="7d">7 Days</TabsTrigger>
            <TabsTrigger value="30d">30 Days</TabsTrigger>
            <TabsTrigger value="90d">90 Days</TabsTrigger>
          </TabsList>

          {(['7d', '30d', '90d'] as TimeFrame[]).map((timeFrame) => (
            <TabsContent key={timeFrame} value={timeFrame}>
              <div className="h-[400px]">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart
                    data={chartData[timeFrame]}
                    margin={{
                      top: 5,
                      right: 30,
                      left: 20,
                      bottom: 5,
                    }}
                  >
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis
                      dataKey="date"
                      tickFormatter={formatDate}
                      interval={timeFrame === '7d' ? 0 : 'preserveEnd'}
                    />
                    <YAxis
                      tickFormatter={formatCurrency}
                    />
                    <Tooltip
                      formatter={(value: number) => [formatCurrency(value)]}
                      labelFormatter={formatDate}
                    />
                    <Legend />
                    <Line
                      type="monotone"
                      dataKey="amount"
                      name="Daily Total"
                      stroke="#2563eb"
                      strokeWidth={2}
                      dot={false}
                    />
                    <Line
                      type="monotone"
                      dataKey="movingAverage"
                      name="7-Day Average"
                      stroke="#16a34a"
                      strokeWidth={2}
                      dot={false}
                      strokeDasharray="5 5"
                    />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </TabsContent>
          ))}
        </Tabs>
      </CardContent>
    </Card>
  );
}
