// src/lib/components/layout/Sidebar.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { page } from '$app/stores';
  import { goto } from '$app/navigation';
  import { currentUser, isAuthenticated } from '$lib/stores/auth';
  import { theme, toggleTheme } from '$lib/stores/settings';
  import { signOut } from '$lib/auth/auth-service';

  // Assuming shadcn-svelte & lucide-svelte
  import { Button } from '$lib/components/ui/button';
  import { Avatar, AvatarFallback, AvatarImage } from '$lib/components/ui/avatar';
  import {
    LayoutDashboard, // Home/Dashboard icon
    Briefcase,     // Trips icon
    Receipt,       // Expenses icon
    Car,           // Mileage icon
    User,          // Profile icon
    Settings,      // Settings icon
    LogOut,
    Moon,
    Sun,
    Laptop,        // System theme icon
    Menu,          // Mobile toggle icon
    X             // Mobile close icon
  } from 'lucide-svelte';

  // Props & Events for mobile state (to be managed by parent layout)
  export let isOpen = false; // Controls visibility on mobile
  const dispatch = createEventDispatcher<{ toggle: void }>();

  function closeSidebar() {
      // Only dispatch toggle if it's currently open (on mobile)
      if (isOpen) {
          dispatch('toggle');
      }
  }

  function navigateAndClose(path: string) {
    goto(path);
    closeSidebar();
  }

  async function handleSignOut() {
      closeSidebar();
      try {
          await signOut();
          goto('/auth'); // Redirect to auth page after sign out
      } catch (error) {
          console.error("Sign out error:", error);
          // TODO: Show error toast
      }
  }

  function getThemeIcon(currentTheme: string) {
      if (currentTheme === 'light') return Sun;
      if (currentTheme === 'dark') return Moon;
      return Laptop;
  }

  // Navigation items
  const navItems = [
    { path: '/dashboard', label: 'Dashboard', icon: LayoutDashboard },
    { path: '/trips', label: 'Trips', icon: Briefcase },
    { path: '/expenses', label: 'Expenses', icon: Receipt },
    { path: '/mileage', label: 'Mileage Logs', icon: Car },
    { path: '/profile', label: 'Profile', icon: User },
    { path: '/settings', label: 'Settings', icon: Settings },
  ];

</script>

<!-- Sidebar -->
<!-- Base classes + conditional classes for mobile open/close state -->
<aside class={`bg-card text-card-foreground border-r w-64 flex-shrink-0 flex flex-col h-screen transition-transform duration-300 ease-in-out fixed md:sticky top-0 left-0 z-50 ${isOpen ? 'translate-x-0' : '-translate-x-full'} md:translate-x-0`}>

  <!-- Logo/Header -->
  <div class="p-4 border-b h-16 flex items-center justify-between">
    <a href="/" class="flex items-center space-x-2" on:click|preventDefault={() => navigateAndClose('/')}>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-primary" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
      <h1 class="text-xl font-bold">ExpenseTracker</h1>
    </a>
     <!-- Close button for mobile -->
     <Button variant="ghost" size="icon" class="md:hidden" on:click={closeSidebar}>
        <X class="h-6 w-6" />
     </Button>
  </div>

  <!-- User Info / Auth Section -->
  <div class="p-4 border-b">
    {#if $isAuthenticated && $currentUser}
      <div class="flex items-center space-x-3">
         <Avatar class="h-10 w-10">
            <AvatarImage src={$currentUser.photoURL || undefined} alt={$currentUser.displayName || 'User'} />
            <AvatarFallback>{($currentUser.displayName || $currentUser.email || 'U').charAt(0).toUpperCase()}</AvatarFallback>
         </Avatar>
         <div>
            <p class="font-semibold text-sm">{$currentUser.displayName || 'User'}</p>
            <p class="text-xs text-muted-foreground">{$currentUser.email}</p>
         </div>
      </div>
       <Button variant="outline" size="sm" class="w-full mt-3" on:click={handleSignOut}>
          <LogOut class="mr-2 h-4 w-4" /> Sign Out
       </Button>
    {:else}
       <Button class="w-full" on:click={() => navigateAndClose('/auth')}>Sign In / Sign Up</Button>
    {/if}
  </div>

  <!-- Navigation -->
  <nav class="p-2 space-y-1 flex-grow overflow-y-auto">
    {#each navItems as item (item.path)}
      <Button
        variant={$page.url.pathname === item.path || (item.path !== '/' && $page.url.pathname.startsWith(item.path)) ? 'secondary' : 'ghost'}
        class="w-full justify-start"
        on:click={() => navigateAndClose(item.path)}
      >
        <svelte:component this={item.icon} class="mr-3 h-5 w-5" />
        <span>{item.label}</span>
      </Button>
    {/each}
  </nav>

  <!-- Footer Actions (Theme Toggle) -->
  <div class="mt-auto p-4 border-t">
    <Button variant="ghost" class="w-full justify-start" on:click={toggleTheme}>
      <svelte:component this={getThemeIcon($theme)} class="mr-2 h-5 w-5" />
      {#if $theme === 'light'} Switch to Dark
      {:else if $theme === 'dark'} Use System Theme
      {:else} Switch to Light
      {/if}
    </Button>
  </div>
</aside>

<!-- Overlay for mobile -->
{#if isOpen}
    <div aria-hidden="true" class="fixed inset-0 bg-black/50 z-40 md:hidden" on:click={closeSidebar}></div>
{/if}

// client/src/components/sidebar.tsx
import { useLocation } from "wouter";
// Removed: import { useAuth } from "@/hooks/use-auth";
import { useAuth, UserButton, SignedIn, SignedOut } from "@clerk/clerk-react"; // Import Clerk components/hooks
import { useSettingsStore, useSidebarStore } from "@/lib/store";
import { Button } from "@/components/ui/button";
import { UserIcon, LogOut, Moon, Sun, Car } from "lucide-react"; // Keep LogOut for SignedOut state if needed

export default function Sidebar() {
  const [location] = useLocation();
  // Removed: const { user, logoutMutation } = useAuth();
  const { theme, toggleTheme } = useSettingsStore();
  const { isOpen, toggle, close } = useSidebarStore();

  // Removed: handleLogout function (Clerk's UserButton handles this)

  const isActiveRoute = (path: string) => {
    return location === path;
  };

  // Helper function for navigation and closing sidebar
  const navigateAndClose = (path: string) => {
    window.location.href = path; // Consider using wouter's navigate for SPA behavior
    close();
  };

  return (
    <>
      {/* Mobile Header */}
      <div className="md:hidden w-full bg-white dark:bg-gray-800 p-4 flex items-center justify-between shadow-md">
        <div className="flex items-center">
          <Button variant="ghost" size="icon" onClick={toggle} className="mr-3">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
            </svg>
          </Button>
          <h1 className="text-lg font-bold">ExpenseTracker</h1>
        </div>
        <div className="flex items-center space-x-2">
           <Button variant="ghost" size="icon" onClick={toggleTheme}>
             {theme === "dark" ? <Sun className="h-5 w-5" /> : <Moon className="h-5 w-5" />}
           </Button>
           {/* Add UserButton to mobile header */}
           <SignedIn>
             <UserButton afterSignOutUrl="/auth" />
           </SignedIn>
           <SignedOut>
             {/* Optionally add a sign-in button here for mobile header */}
           </SignedOut>
         </div>
      </div>

      {/* Sidebar Overlay for Mobile */}
      {isOpen && (
        <div className="fixed inset-0 bg-black bg-opacity-50 z-40 md:hidden" onClick={close}></div>
      )}

      {/* Sidebar */}
      <aside className={`bg-white dark:bg-gray-800 w-full md:w-64 shadow-md md:shadow-none md:flex md:flex-col flex-shrink-0 md:h-screen overflow-y-auto transition-all duration-300 z-50 fixed md:relative inset-0 ${isOpen ? 'translate-x-0' : '-translate-x-full md:translate-x-0'}`}>
        <div className="p-4 border-b dark:border-gray-700">
          <div className="flex items-center space-x-2">
            <span className="text-primary text-2xl">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </span>
            <h1 className="text-xl font-bold">ExpenseTracker</h1>
          </div>
        </div>

        {/* Use Clerk's SignedIn component to show user info */}
        <SignedIn>
          <div className="p-4 border-b dark:border-gray-700">
             {/* Use Clerk's UserButton for profile management and sign out */}
             <UserButton afterSignOutUrl="/auth" />
           </div>
        </SignedIn>
        {/* Optionally show something different when signed out */}
        {/* <SignedOut>
          <div className="p-4 border-b dark:border-gray-700">
             <p>Please sign in</p>
           </div>
        </SignedOut> */}

        <nav className="p-2 space-y-1 flex-grow"> {/* Added flex-grow */}
          <div
            className={`flex items-center p-3 rounded-lg cursor-pointer ${
              isActiveRoute("/")
                ? "text-primary bg-blue-50 dark:bg-blue-900/20"
                : "hover:bg-gray-100 dark:hover:bg-gray-700"
            }`}
            onClick={() => navigateAndClose("/")}
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
            </svg>
            <span>Dashboard</span>
          </div>

          <div
            className={`flex items-center p-3 rounded-lg cursor-pointer ${
              isActiveRoute("/trips")
                ? "text-primary bg-blue-50 dark:bg-blue-900/20"
                : "hover:bg-gray-100 dark:hover:bg-gray-700"
            }`}
            onClick={() => navigateAndClose("/trips")}
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
            </svg>
            <span>Trips</span>
          </div>

          <div
            className={`flex items-center p-3 rounded-lg cursor-pointer ${
              isActiveRoute("/expenses")
                ? "text-primary bg-blue-50 dark:bg-blue-900/20"
                : "hover:bg-gray-100 dark:hover:bg-gray-700"
            }`}
            onClick={() => navigateAndClose("/expenses")}
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
            </svg>
            <span>Expenses</span>
          </div>

          {/* Mileage Logs Link */}
          <div
            className={`flex items-center p-3 rounded-lg cursor-pointer ${
              isActiveRoute("/mileage-logs")
                ? "text-primary bg-blue-50 dark:bg-blue-900/20"
                : "hover:bg-gray-100 dark:hover:bg-gray-700"
            }`}
            onClick={() => navigateAndClose("/mileage-logs")}
          >
            <Car className="h-5 w-5 mr-3" /> {/* Use Car icon */}
            <span>Mileage Logs</span>
          </div>

          {/* Profile Link */}
          <div
            className={`flex items-center p-3 rounded-lg cursor-pointer ${
              isActiveRoute("/profile")
                ? "text-primary bg-blue-50 dark:bg-blue-900/20"
                : "hover:bg-gray-100 dark:hover:bg-gray-700"
            }`}
            onClick={() => navigateAndClose("/profile")}
          >
            <UserIcon className="h-5 w-5 mr-3" />
            <span>Profile</span>
          </div>

          {/* Settings Link */}
          <div
            className={`flex items-center p-3 rounded-lg cursor-pointer ${
              isActiveRoute("/settings")
                ? "text-primary bg-blue-50 dark:bg-blue-900/20"
                : "hover:bg-gray-100 dark:hover:bg-gray-700"
            }`}
            onClick={() => navigateAndClose("/settings")}
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
            </svg>
            <span>Settings</span>
          </div>
        </nav>

        <div className="mt-auto p-4 border-t dark:border-gray-700">
          <Button variant="ghost" className="w-full justify-start" onClick={toggleTheme}>
            {theme === "dark" ? (
              <>
                <Sun className="mr-2 h-5 w-5" />
                <span>Light Mode</span>
              </>
            ) : (
              <>
                <Moon className="mr-2 h-5 w-5" />
                <span>Dark Mode</span>
              </>
            )}
          </Button>

          {/* Removed manual Logout button - UserButton handles this */}
          {/* <SignedIn>
            <Button
              variant="ghost"
              className="w-full justify-start mt-2"
              // onClick={handleLogout} // UserButton handles logout
              // disabled={logoutMutation.isPending}
            >
              <LogOut className="mr-2 h-5 w-5" />
              <span>Logout</span>
            </Button>
          </SignedIn> */}
        </div>
      </aside>
    </>
  );
}
